# Generated by Django 5.0.4 on 2024-04-06 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
