# Generated by Django 5.0.4 on 2024-04-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_student",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
