# Generated by Django 5.0.4 on 2024-05-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0003_alter_message_related_chat_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsystem',
            name='chat_enable',
            field=models.BooleanField(default=True),
        ),
    ]
