# Generated by Django 5.0.4 on 2024-04-20 23:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "eduportal",
            "0002_position_fee_student_enrollment_date_student_gender_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="date_applied",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="request",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("P", "Pending"), ("R", "Rejected"), ("A", "Accepted")],
                default="P",
                max_length=1,
                null=True,
            ),
        ),
    ]
