# Generated by Django 5.0.4 on 2024-04-17 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0003_alter_position_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="id",
        ),
        migrations.AlterField(
            model_name="tag",
            name="label",
            field=models.CharField(max_length=31, primary_key=True, serialize=False),
        ),
    ]
