# Generated by Django 5.0.4 on 2024-04-17 13:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0003_tag_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="tags",
            field=models.ManyToManyField(blank=True, to="eduportal.tag"),
        ),
    ]
