# Generated by Django 5.0.4 on 2024-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0004_alter_student_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='share_with_others',
            field=models.BooleanField(default=False),
        ),
    ]
