# Generated by Django 5.0.4 on 2024-04-19 00:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0002_student"),
        ("eduportal", "0006_position_tags"),
    ]

    operations = []
