# Generated by Django 5.0.4 on 2024-05-04 09:52

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0007_rename_deadline_position_end_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("image", models.ImageField(upload_to="universities/")),
                ("icon", models.ImageField(upload_to="universities/")),
                ("website_url", models.URLField(max_length=255)),
                ("rank", models.IntegerField()),
                ("city", models.CharField(max_length=63)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("total_student_count", models.IntegerField()),
                ("international_student_count", models.IntegerField()),
            ],
        ),
    ]
