# Generated by Django 5.0.4 on 2024-04-19 01:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0007_merge_0002_student_0006_position_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="duration",
            field=models.DurationField(default="00:00"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="position",
            name="starts_at",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
