# Generated by Django 5.0.4 on 2024-04-19 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0008_position_duration_position_starts_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('R', 'Rather not to say')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='major',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('SE', 'Software Engineering'), ('ME', 'Mechanical Engineering'), ('EE', 'Electrical Engineering'), ('CE', 'Civil Engineering'), ('AE', 'Aerospace Engineering'), ('BIO', 'Biology'), ('CHEM', 'Chemistry'), ('PHYS', 'Physics'), ('MATH', 'Mathematics'), ('STAT', 'Statistics'), ('ECON', 'Economics'), ('PSY', 'Psychology'), ('SOC', 'Sociology'), ('POL', 'Political Science'), ('PHIL', 'Philosophy'), ('ENG', 'English'), ('HIST', 'History'), ('ART', 'Art'), ('MUS', 'Music'), ('THEA', 'Theatre'), ('EDU', 'Education'), ('BUS', 'Business'), ('ACC', 'Accounting'), ('FIN', 'Finance'), ('MKT', 'Marketing'), ('HRM', 'Human Resource Management'), ('IB', 'International Business'), ('ENT', 'Entrepreneurship')], max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('I', 'Inactive'), ('G', 'Graduated')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('R', 'Rejected'), ('A', 'Accepted')], default='P', max_length=1)),
                ('date_applied', models.DateTimeField(auto_now_add=True)),
                ('cover_letter', models.TextField()),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduportal.position')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduportal.student')),
            ],
        ),
    ]
