# Generated by Django 5.0.4 on 2024-05-06 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0010_professor_university"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("R", "Rather not to say"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("E", "Employed"),
                            ("U", "Unemployed"),
                            ("S", "Student"),
                            ("AS", "Actively Seeking Work"),
                            ("OW", "Open to Work"),
                            ("NI", "Not Interested"),
                        ],
                        max_length=2,
                        null=True,
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "professor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv",
                        to="eduportal.professor",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv",
                        to="eduportal.student",
                    ),
                ),
                ("soft_skills", models.ManyToManyField(to="eduportal.softskill")),
            ],
        ),
        migrations.CreateModel(
            name="EducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("field_of_study", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("grade", models.FloatField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_histories",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("technology", models.CharField(max_length=255)),
                ("skill_level", models.IntegerField()),
                ("experience_time", models.DurationField()),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_skills",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_experiences",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("company_website", models.URLField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("job_title", models.CharField(max_length=255)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
    ]
