# Generated by Django 5.0.4 on 2024-05-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0011_cv_educationhistory_hardskill_projectexperience_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cv",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cv",
            name="employment_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("E", "Employed"),
                    ("U", "Unemployed"),
                    ("S", "Student"),
                    ("AS", "Actively Seeking Work"),
                    ("OW", "Open to Work"),
                    ("NI", "Not Interested"),
                ],
                max_length=2,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female"), ("R", "Rather not to say")],
                max_length=1,
                null=True,
            ),
        ),
    ]
