# Generated by Django 5.0.4 on 2024-05-08 13:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0011_softskill_cv_educationhistory_hardskill_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="professor",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="soft_skills",
        ),
        migrations.RemoveField(
            model_name="cv",
            name="student",
        ),
        migrations.RemoveField(
            model_name="educationhistory",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="hardskill",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="projectexperience",
            name="cv",
        ),
        migrations.RemoveField(
            model_name="workexperience",
            name="cv",
        ),
        migrations.DeleteModel(
            name="SoftSkill",
        ),
        migrations.DeleteModel(
            name="EducationHistory",
        ),
        migrations.DeleteModel(
            name="HardSkill",
        ),
        migrations.DeleteModel(
            name="ProjectExperience",
        ),
        migrations.DeleteModel(
            name="CV",
        ),
        migrations.DeleteModel(
            name="WorkExperience",
        ),
    ]
