# Generated by Django 5.0.4 on 2024-05-08 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0012_remove_cv_professor_remove_cv_soft_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoftSkill",
            fields=[
                (
                    "skill",
                    models.IntegerField(
                        choices=[
                            (1, "Communication"),
                            (2, "Teamwork"),
                            (3, "Problem Solving"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CV",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "Male"), (2, "Female"), (3, "Rather Not Say")],
                        null=True,
                    ),
                ),
                (
                    "employment_status",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "Employed"),
                            (2, "Unemployed"),
                            (3, "Student"),
                            (4, "Actively Seeking Work"),
                            (5, "Open To Work"),
                            (6, "Not Interested"),
                        ],
                        null=True,
                    ),
                ),
                ("about", models.TextField(blank=True, null=True)),
                (
                    "professor",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv",
                        to="eduportal.professor",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv",
                        to="eduportal.student",
                    ),
                ),
                ("soft_skills", models.ManyToManyField(to="eduportal.softskill")),
            ],
        ),
        migrations.CreateModel(
            name="EducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("institute", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("field_of_study", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("grade", models.FloatField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_histories",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HardSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "technology",
                    models.IntegerField(
                        choices=[
                            (1, "Python"),
                            (2, "Django"),
                            (3, "Flask"),
                            (4, "Javascript"),
                            (5, "React"),
                            (6, "Angular"),
                            (7, "Vue"),
                            (8, "Java"),
                            (9, "Spring"),
                            (10, "Hibernate"),
                            (11, "C"),
                            (12, "Cpp"),
                            (13, "Csharp"),
                            (14, "Dotnet"),
                            (15, "Ruby"),
                            (16, "Rails"),
                            (17, "Php"),
                            (18, "Laravel"),
                            (19, "Swift"),
                            (20, "Kotlin"),
                            (21, "Go"),
                            (22, "Rust"),
                            (23, "Scala"),
                            (24, "Groovy"),
                            (25, "Typescript"),
                            (26, "Nodejs"),
                            (27, "Express"),
                            (28, "Ruby On Rails"),
                            (29, "Sql"),
                            (30, "Nosql"),
                        ]
                    ),
                ),
                ("skill_level", models.IntegerField()),
                (
                    "experience_time",
                    models.IntegerField(
                        choices=[
                            (1, "Less Than A Year"),
                            (2, "Between 1 And 5 Years"),
                            (3, "More Than 5 Years"),
                        ]
                    ),
                ),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hard_skills",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_experiences",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("company_website", models.URLField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("job_title", models.CharField(max_length=255)),
                (
                    "cv",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_experiences",
                        to="eduportal.cv",
                    ),
                ),
            ],
        ),
    ]
