# Generated by Django 5.0.4 on 2024-05-08 14:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0013_softskill_cv_educationhistory_hardskill_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hardskill",
            name="skill_level",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
    ]
