# Generated by Django 5.0.4 on 2024-05-11 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0014_alter_hardskill_skill_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='university_name',
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduportal.university'),
        ),
    ]
