# Generated by Django 5.0.4 on 2024-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0016_languageskill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('SP', 'Student Pending'), ('SR', 'Student Rejected'), ('SA', 'Student Accepted'), ('PP', 'Professor Pending'), ('PR', 'Professor Rejected'), ('PA', 'Professor Accepted')], default='PP', max_length=2),
        ),
    ]
