# Generated by Django 5.0.4 on 2024-05-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0017_alter_request_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag2",
            fields=[
                (
                    "label",
                    models.IntegerField(
                        choices=[
                            (1, "Artificial Intelligence"),
                            (2, "Data Science"),
                            (3, "Machine Learning"),
                            (4, "Cyber Security"),
                            (5, "Software Engineering"),
                            (6, "Cloud Computing"),
                            (7, "Quantum Computing"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="position",
            name="tags2",
            field=models.ManyToManyField(to="eduportal.tag2"),
        ),
    ]
