# Generated by Django 5.0.4 on 2024-05-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0019_student_interest_tags_notification_notificationitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'Student Created Request'), (2, 'Professor Accepted Request'), (-2, 'Professor Rejected Request'), (3, 'Student Accepted Request'), (-3, 'Student Rejected Request'), (4, 'New Tagged Post')]),
        ),
    ]
