# Generated by Django 5.0.4 on 2024-05-15 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0019_student_interest_tags_notification_notificationitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="bookmarked",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.IntegerField(
                choices=[
                    (1, "Student Created Request"),
                    (2, "Professor Accepted Request"),
                    (-2, "Professor Rejected Request"),
                    (3, "Student Accepted Request"),
                    (-3, "Student Rejected Request"),
                    (4, "New Tagged Post"),
                ]
            ),
        ),
    ]
