# Generated by Django 5.0.4 on 2024-05-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0024_alter_position_tags2'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profileImage/'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='profileImage/'),
        ),
    ]
