# Generated by Django 5.0.4 on 2024-05-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("eduportal", "0025_professor_profile_image_student_profile_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="soft_skills",
            field=models.ManyToManyField(blank=True, to="eduportal.softskill"),
        ),
        migrations.AlterField(
            model_name="student",
            name="interest_tags",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="eduportal.tag2"
            ),
        ),
    ]
