# Generated by Django 5.0.4 on 2024-05-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0026_alter_cv_soft_skills_alter_student_interest_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(blank=True, choices=[('SP', 'Pending Student Response'), ('SR', 'Student Rejected'), ('SA', 'Student Accepted'), ('PP', 'Pending Professor Response'), ('PR', 'Professor Rejected'), ('PA', 'Professor Accepted')], default='PP', max_length=2),
        ),
    ]
