# Generated by Django 5.0.4 on 2024-05-30 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0027_alter_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='image/')),
            ],
        ),
        migrations.RemoveField(
            model_name='professor',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
