# Generated by Django 5.0.4 on 2024-05-30 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0028_image_remove_professor_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='profile_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduportal.image'),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='eduportal.image'),
        ),
    ]
