# Generated by Django 5.0.4 on 2024-06-05 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0029_professor_profile_image_student_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
