# Generated by Django 5.0.4 on 2024-06-05 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduportal', '0030_remove_professor_profile_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
