MAJORS = [
    ('CS', 'Computer Science'),
    ('SE', 'Software Engineering'),
    ('ME', 'Mechanical Engineering'),
    ('EE', 'Electrical Engineering'),
    ('CE', 'Civil Engineering'),
    ('AE', 'Aerospace Engineering'),
    ('BIO', 'Biology'),
    ('CHEM', 'Chemistry'),
    ('PHYS', 'Physics'),
    ('MATH', 'Mathematics'),
    ('STAT', 'Statistics'),
    ('ECON', 'Economics'),
    ('PSY', 'Psychology'),
    ('SOC', 'Sociology'),
    ('POL', 'Political Science'),
    ('PHIL', 'Philosophy'),
    ('ENG', 'English'),
    ('HIST', 'History'),
    ('ART', 'Art'),
    ('MUS', 'Music'),
    ('THEA', 'Theatre'),
    ('EDU', 'Education'),
    ('BUS', 'Business'),
    ('ACC', 'Accounting'),
    ('FIN', 'Finance'),
    ('MKT', 'Marketing'),
    ('HRM', 'Human Resource Management'),
    ('IB', 'International Business'),
    ('ENT', 'Entrepreneurship'),
]
